import type {City, Continent, FilterCategory} from "./types"

export const cities: City[] = [
    // Asia (15 cities)
    {
        id: "bangkok-thailand",           // 고유 식별자 (kebab-case 형식, 라우팅 및 이미지 매칭에 사용)
        name: "Bangkok",                  // 도시명 (영문)
        country: "Thailand",              // 국가명 (영문)
        continent: "Asia",                // 대륙 (Asia, Europe, North America 등)
        cost: 1200,                       // 월 생활비 (USD 단위)
        temperature: 32,                  // 평균 온도 (섭씨 °C)
        feelsLike: 38,                    // 체감 온도 (섭씨 °C, 습도 등을 고려한 선택적 필드)
        internetSpeed: 45,                // 인터넷 속도 (Mbps 단위)
        airQuality: 85,                   // 공기질 지수 (AQI, 0-50: 좋음, 51-100: 보통, 101+: 나쁨)
        nomadScore: 4.2,                  // 디지털 노마드 종합 점수 (1.0 ~ 5.0)
        image: "/cities/bangkok-thailand.jpg",  // 도시 이미지 경로 (public 폴더 기준 상대 경로)
        safety: "medium",                 // 안전도 레벨 ("low", "medium", "high" 중 하나)
        weather: "hot",                   // 날씨 카테고리 ("cold", "mild", "warm", "hot" 중 하나)
    },
    {
        id: "chiang-mai-thailand",
        name: "Chiang Mai",
        country: "Thailand",
        continent: "Asia",
        cost: 800,
        temperature: 28,
        feelsLike: 32,
        internetSpeed: 35,
        airQuality: 65,
        nomadScore: 4.5,
        image: "/cities/chiang-mai-thailand.jpg",
        safety: "high",
        weather: "warm",
    },
    {
        id: "kuala-lumpur-malaysia",
        name: "Kuala Lumpur",
        country: "Malaysia",
        continent: "Asia",
        cost: 1100,
        temperature: 30,
        feelsLike: 35,
        internetSpeed: 50,
        airQuality: 78,
        nomadScore: 4.0,
        image: "/cities/kuala-lumpur-malaysia.jpg",
        safety: "medium",
        weather: "hot",
    },
    {
        id: "canggu-indonesia",
        name: "Canggu",
        country: "Indonesia",
        continent: "Asia",
        cost: 900,
        temperature: 29,
        feelsLike: 33,
        internetSpeed: 25,
        airQuality: 45,
        nomadScore: 4.3,
        image: "/cities/canggu-indonesia.jpg",
        safety: "medium",
        weather: "warm",
    },
    {
        id: "seoul-south-korea",
        name: "Seoul",
        country: "South Korea",
        continent: "Asia",
        cost: 2200,
        temperature: 15,
        feelsLike: 18,
        internetSpeed: 95,
        airQuality: 68,
        nomadScore: 3.8,
        image: "/cities/seoul-south-korea.jpg",
        safety: "high",
        weather: "mild",
    },
    {
        id: "tokyo-japan",
        name: "Tokyo",
        country: "Japan",
        continent: "Asia",
        cost: 3500,
        temperature: 18,
        feelsLike: 20,
        internetSpeed: 85,
        airQuality: 42,
        nomadScore: 3.5,
        image: "/cities/tokyo-japan.jpg",
        safety: "high",
        weather: "mild",
    },
    {
        id: "ho-chi-minh-vietnam",
        name: "Ho Chi Minh City",
        country: "Vietnam",
        continent: "Asia",
        cost: 700,
        temperature: 31,
        feelsLike: 36,
        internetSpeed: 30,
        airQuality: 88,
        nomadScore: 4.1,
        image: "/cities/ho-chi-minh-vietnam.jpg",
        safety: "medium",
        weather: "hot",
    },
    {
        id: "singapore-singapore",
        name: "Singapore",
        country: "Singapore",
        continent: "Asia",
        cost: 3800,
        temperature: 30,
        feelsLike: 35,
        internetSpeed: 120,
        airQuality: 35,
        nomadScore: 3.2,
        image: "/cities/singapore-singapore.jpg",
        safety: "high",
        weather: "hot",
    },
    {
        id: "taipei-taiwan",
        name: "Taipei",
        country: "Taiwan",
        continent: "Asia",
        cost: 1800,
        temperature: 24,
        feelsLike: 28,
        internetSpeed: 75,
        airQuality: 55,
        nomadScore: 3.9,
        image: "/cities/taipei-taiwan.jpg",
        safety: "high",
        weather: "warm",
    },
    {
        id: "manila-philippines",
        name: "Manila",
        country: "Philippines",
        continent: "Asia",
        cost: 950,
        temperature: 31,
        feelsLike: 37,
        internetSpeed: 28,
        airQuality: 92,
        nomadScore: 3.6,
        image: "/cities/manila-philippines.jpg",
        safety: "medium",
        weather: "hot",
    },
    {
        id: "mumbai-india",
        name: "Mumbai",
        country: "India",
        continent: "Asia",
        cost: 800,
        temperature: 29,
        feelsLike: 34,
        internetSpeed: 40,
        airQuality: 105,
        nomadScore: 3.4,
        image: "/cities/mumbai-india.jpg",
        safety: "medium",
        weather: "hot",
    },
    {
        id: "colombo-sri-lanka",
        name: "Colombo",
        country: "Sri Lanka",
        continent: "Asia",
        cost: 650,
        temperature: 30,
        feelsLike: 35,
        internetSpeed: 22,
        airQuality: 58,
        nomadScore: 3.7,
        image: "/cities/colombo-sri-lanka.jpg",
        safety: "medium",
        weather: "hot",
    },
    {
        id: "hong-kong-china",
        name: "Hong Kong",
        country: "China",
        continent: "Asia",
        cost: 4200,
        temperature: 26,
        feelsLike: 30,
        internetSpeed: 110,
        airQuality: 72,
        nomadScore: 3.1,
        image: "/cities/hong-kong-china.jpg",
        safety: "high",
        weather: "warm",
    },
    {
        id: "beijing-china",
        name: "Beijing",
        country: "China",
        continent: "Asia",
        cost: 2100,
        temperature: 12,
        feelsLike: 15,
        internetSpeed: 65,
        airQuality: 115,
        nomadScore: 3.0,
        image: "/cities/beijing-china.jpg",
        safety: "medium",
        weather: "mild",
    },
    {
        id: "dhaka-bangladesh",
        name: "Dhaka",
        country: "Bangladesh",
        continent: "Asia",
        cost: 500,
        temperature: 28,
        feelsLike: 33,
        internetSpeed: 18,
        airQuality: 125,
        nomadScore: 2.8,
        image: "/cities/dhaka-bangladesh.jpg",
        safety: "low",
        weather: "warm",
    },

    // Europe (12 cities)
    {
        id: "berlin-germany",
        name: "Berlin",
        country: "Germany",
        continent: "Europe",
        cost: 2800,
        temperature: 12,
        feelsLike: 10,
        internetSpeed: 65,
        airQuality: 28,
        nomadScore: 4.1,
        image: "/cities/berlin-germany.jpg",
        safety: "high",
        weather: "mild",
    },
    {
        id: "lisbon-portugal",
        name: "Lisbon",
        country: "Portugal",
        continent: "Europe",
        cost: 2200,
        temperature: 19,
        feelsLike: 22,
        internetSpeed: 55,
        airQuality: 25,
        nomadScore: 4.4,
        image: "/cities/lisbon-portugal.jpg",
        safety: "high",
        weather: "mild",
    },
    {
        id: "porto-portugal",
        name: "Porto",
        country: "Portugal",
        continent: "Europe",
        cost: 1900,
        temperature: 17,
        feelsLike: 20,
        internetSpeed: 50,
        airQuality: 22,
        nomadScore: 4.3,
        image: "/cities/porto-portugal.jpg",
        safety: "high",
        weather: "mild",
    },
    {
        id: "barcelona-spain",
        name: "Barcelona",
        country: "Spain",
        continent: "Europe",
        cost: 2600,
        temperature: 21,
        feelsLike: 24,
        internetSpeed: 60,
        airQuality: 35,
        nomadScore: 4.2,
        image: "/cities/barcelona-spain.jpg",
        safety: "medium",
        weather: "warm",
    },
    {
        id: "london-uk",
        name: "London",
        country: "United Kingdom",
        continent: "Europe",
        cost: 4500,
        temperature: 13,
        feelsLike: 11,
        internetSpeed: 70,
        airQuality: 32,
        nomadScore: 3.6,
        image: "/cities/london-uk.jpg",
        safety: "high",
        weather: "mild",
    },
    {
        id: "amsterdam-netherlands",
        name: "Amsterdam",
        country: "Netherlands",
        continent: "Europe",
        cost: 3200,
        temperature: 11,
        feelsLike: 9,
        internetSpeed: 85,
        airQuality: 18,
        nomadScore: 3.9,
        image: "/cities/amsterdam-netherlands.jpg",
        safety: "high",
        weather: "mild",
    },
    {
        id: "prague-czech-republic",
        name: "Prague",
        country: "Czech Republic",
        continent: "Europe",
        cost: 1800,
        temperature: 10,
        feelsLike: 8,
        internetSpeed: 45,
        airQuality: 30,
        nomadScore: 4.0,
        image: "/cities/prague-czech-republic.jpg",
        safety: "high",
        weather: "mild",
    },
    {
        id: "budapest-hungary",
        name: "Budapest",
        country: "Hungary",
        continent: "Europe",
        cost: 1600,
        temperature: 12,
        feelsLike: 10,
        internetSpeed: 55,
        airQuality: 38,
        nomadScore: 3.8,
        image: "/cities/budapest-hungary.jpg",
        safety: "medium",
        weather: "mild",
    },
    {
        id: "warsaw-poland",
        name: "Warsaw",
        country: "Poland",
        continent: "Europe",
        cost: 1500,
        temperature: 9,
        feelsLike: 7,
        internetSpeed: 48,
        airQuality: 42,
        nomadScore: 3.5,
        image: "/cities/warsaw-poland.jpg",
        safety: "medium",
        weather: "cold",
    },
    {
        id: "rome-italy",
        name: "Rome",
        country: "Italy",
        continent: "Europe",
        cost: 2400,
        temperature: 18,
        feelsLike: 21,
        internetSpeed: 42,
        airQuality: 45,
        nomadScore: 3.7,
        image: "/cities/rome-italy.jpg",
        safety: "medium",
        weather: "mild",
    },
    {
        id: "stockholm-sweden",
        name: "Stockholm",
        country: "Sweden",
        continent: "Europe",
        cost: 3800,
        temperature: 6,
        feelsLike: 4,
        internetSpeed: 75,
        airQuality: 15,
        nomadScore: 3.4,
        image: "/cities/stockholm-sweden.jpg",
        safety: "high",
        weather: "cold",
    },
    {
        id: "zurich-switzerland",
        name: "Zurich",
        country: "Switzerland",
        continent: "Europe",
        cost: 5200,
        temperature: 8,
        feelsLike: 6,
        internetSpeed: 90,
        airQuality: 12,
        nomadScore: 3.2,
        image: "/cities/zurich-switzerland.jpg",
        safety: "high",
        weather: "cold",
    },

    // North America (8 cities)
    {
        id: "new-york-usa",
        name: "New York",
        country: "United States",
        continent: "North America",
        cost: 5500,
        temperature: 14,
        feelsLike: 12,
        internetSpeed: 80,
        airQuality: 48,
        nomadScore: 3.3,
        image: "/cities/new-york-usa.jpg",
        safety: "medium",
        weather: "mild",
    },
    {
        id: "mexico-city-mexico",
        name: "Mexico City",
        country: "Mexico",
        continent: "North America",
        cost: 1400,
        temperature: 20,
        feelsLike: 23,
        internetSpeed: 35,
        airQuality: 95,
        nomadScore: 4.0,
        image: "/cities/mexico-city-mexico.jpg",
        safety: "medium",
        weather: "warm",
    },
    {
        id: "toronto-canada",
        name: "Toronto",
        country: "Canada",
        continent: "North America",
        cost: 3200,
        temperature: 8,
        feelsLike: 5,
        internetSpeed: 65,
        airQuality: 25,
        nomadScore: 3.6,
        image: "/cities/toronto-canada.jpg",
        safety: "high",
        weather: "cold",
    },
    {
        id: "san-francisco-usa",
        name: "San Francisco",
        country: "United States",
        continent: "North America",
        cost: 6200,
        temperature: 16,
        feelsLike: 18,
        internetSpeed: 95,
        airQuality: 38,
        nomadScore: 3.1,
        image: "/cities/san-francisco-usa.jpg",
        safety: "medium",
        weather: "mild",
    },
    {
        id: "austin-usa",
        name: "Austin",
        country: "United States",
        continent: "North America",
        cost: 3800,
        temperature: 22,
        feelsLike: 25,
        internetSpeed: 75,
        airQuality: 42,
        nomadScore: 3.7,
        image: "/cities/austin-usa.jpg",
        safety: "medium",
        weather: "warm",
    },
    {
        id: "vancouver-canada",
        name: "Vancouver",
        country: "Canada",
        continent: "North America",
        cost: 3600,
        temperature: 11,
        feelsLike: 13,
        internetSpeed: 70,
        airQuality: 22,
        nomadScore: 3.5,
        image: "/cities/vancouver-canada.jpg",
        safety: "high",
        weather: "mild",
    },
    {
        id: "playa-del-carmen-mexico",
        name: "Playa del Carmen",
        country: "Mexico",
        continent: "North America",
        cost: 1200,
        temperature: 28,
        feelsLike: 32,
        internetSpeed: 30,
        airQuality: 35,
        nomadScore: 4.2,
        image: "/cities/playa-del-carmen-mexico.jpg",
        safety: "medium",
        weather: "hot",
    },
    {
        id: "guatemala-city-guatemala",
        name: "Guatemala City",
        country: "Guatemala",
        continent: "North America",
        cost: 900,
        temperature: 22,
        feelsLike: 25,
        internetSpeed: 25,
        airQuality: 68,
        nomadScore: 3.2,
        image: "/cities/guatemala-city-guatemala.jpg",
        safety: "low",
        weather: "warm",
    },

    // South America (6 cities)
    {
        id: "buenos-aires-argentina",
        name: "Buenos Aires",
        country: "Argentina",
        continent: "South America",
        cost: 1100,
        temperature: 18,
        feelsLike: 21,
        internetSpeed: 40,
        airQuality: 52,
        nomadScore: 3.9,
        image: "/cities/buenos-aires-argentina.jpg",
        safety: "medium",
        weather: "mild",
    },
    {
        id: "medellin-colombia",
        name: "Medellin",
        country: "Colombia",
        continent: "South America",
        cost: 800,
        temperature: 24,
        feelsLike: 27,
        internetSpeed: 35,
        airQuality: 58,
        nomadScore: 4.1,
        image: "/cities/medellin-colombia.jpg",
        safety: "medium",
        weather: "warm",
    },
    {
        id: "lima-peru",
        name: "Lima",
        country: "Peru",
        continent: "South America",
        cost: 950,
        temperature: 20,
        feelsLike: 23,
        internetSpeed: 28,
        airQuality: 75,
        nomadScore: 3.6,
        image: "/cities/lima-peru.jpg",
        safety: "medium",
        weather: "mild",
    },
    {
        id: "sao-paulo-brazil",
        name: "São Paulo",
        country: "Brazil",
        continent: "South America",
        cost: 1300,
        temperature: 21,
        feelsLike: 24,
        internetSpeed: 45,
        airQuality: 68,
        nomadScore: 3.4,
        image: "/cities/sao-paulo-brazil.jpg",
        safety: "low",
        weather: "warm",
    },
    {
        id: "santiago-chile",
        name: "Santiago",
        country: "Chile",
        continent: "South America",
        cost: 1600,
        temperature: 16,
        feelsLike: 19,
        internetSpeed: 50,
        airQuality: 85,
        nomadScore: 3.5,
        image: "/cities/santiago-chile.jpg",
        safety: "medium",
        weather: "mild",
    },
    {
        id: "montevideo-uruguay",
        name: "Montevideo",
        country: "Uruguay",
        continent: "South America",
        cost: 1400,
        temperature: 17,
        feelsLike: 20,
        internetSpeed: 38,
        airQuality: 32,
        nomadScore: 3.7,
        image: "/cities/montevideo-uruguay.jpg",
        safety: "high",
        weather: "mild",
    },

    // Africa (4 cities)
    {
        id: "cape-town-south-africa",
        name: "Cape Town",
        country: "South Africa",
        continent: "Africa",
        cost: 1200,
        temperature: 20,
        feelsLike: 23,
        internetSpeed: 32,
        airQuality: 28,
        nomadScore: 3.8,
        image: "/cities/cape-town-south-africa.jpg",
        safety: "medium",
        weather: "warm",
    },
    {
        id: "marrakech-morocco",
        name: "Marrakech",
        country: "Morocco",
        continent: "Africa",
        cost: 800,
        temperature: 26,
        feelsLike: 30,
        internetSpeed: 25,
        airQuality: 65,
        nomadScore: 3.5,
        image: "/cities/marrakech-morocco.jpg",
        safety: "medium",
        weather: "warm",
    },
    {
        id: "nairobi-kenya",
        name: "Nairobi",
        country: "Kenya",
        continent: "Africa",
        cost: 900,
        temperature: 22,
        feelsLike: 25,
        internetSpeed: 20,
        airQuality: 78,
        nomadScore: 3.2,
        image: "/cities/nairobi-kenya.jpg",
        safety: "low",
        weather: "warm",
    },
    {
        id: "lagos-nigeria",
        name: "Lagos",
        country: "Nigeria",
        continent: "Africa",
        cost: 700,
        temperature: 29,
        feelsLike: 34,
        internetSpeed: 18,
        airQuality: 95,
        nomadScore: 2.9,
        image: "/cities/lagos-nigeria.jpg",
        safety: "low",
        weather: "hot",
    },

    // Oceania (3 cities)
    {
        id: "sydney-australia",
        name: "Sydney",
        country: "Australia",
        continent: "Oceania",
        cost: 4200,
        temperature: 22,
        feelsLike: 25,
        internetSpeed: 65,
        airQuality: 22,
        nomadScore: 3.4,
        image: "/cities/sydney-australia.jpg",
        safety: "high",
        weather: "warm",
    },
    {
        id: "melbourne-australia",
        name: "Melbourne",
        country: "Australia",
        continent: "Oceania",
        cost: 3800,
        temperature: 18,
        feelsLike: 21,
        internetSpeed: 60,
        airQuality: 25,
        nomadScore: 3.6,
        image: "/cities/melbourne-australia.jpg",
        safety: "high",
        weather: "mild",
    },
    {
        id: "auckland-new-zealand",
        name: "Auckland",
        country: "New Zealand",
        continent: "Oceania",
        cost: 3600,
        temperature: 16,
        feelsLike: 19,
        internetSpeed: 55,
        airQuality: 18,
        nomadScore: 3.3,
        image: "/cities/auckland-new-zealand.jpg",
        safety: "high",
        weather: "mild",
    },

    // Middle East (2 cities)
    {
        id: "dubai-uae",
        name: "Dubai",
        country: "United Arab Emirates",
        continent: "Middle East",
        cost: 3500,
        temperature: 35,
        feelsLike: 42,
        internetSpeed: 85,
        airQuality: 68,
        nomadScore: 3.1,
        image: "/cities/dubai-uae.jpg",
        safety: "high",
        weather: "hot",
    },
    {
        id: "tel-aviv-israel",
        name: "Tel Aviv",
        country: "Israel",
        continent: "Middle East",
        cost: 3200,
        temperature: 24,
        feelsLike: 27,
        internetSpeed: 70,
        airQuality: 45,
        nomadScore: 3.3,
        image: "/cities/tel-aviv-israel.jpg",
        safety: "medium",
        weather: "warm",
    },
]

export const filterByCategory = (cities: City[], category: FilterCategory): City[] => {
    switch (category) {
        case "cheap":
            return cities.filter((city) => city.cost < 2000)
        case "weather":
            return cities.filter((city) => city.temperature >= 20 && city.temperature <= 28)
        case "internet":
            return cities.filter((city) => city.internetSpeed > 20)
        case "safety":
            return cities.filter((city) => city.safety === "high")
        case "air":
            return cities.filter((city) => city.airQuality < 50)
        case "warm":
            return cities.filter((city) => city.temperature > 25)
        default:
            return cities
    }
}

export const filterByContinent = (cities: City[], continent: Continent): City[] => {
    if (continent === "All") return cities
    return cities.filter((city) => city.continent === continent)
}

export const getContinentCounts = (): Record<Continent, number> => {
    const counts = cities.reduce(
        (acc, city) => {
            acc[city.continent] = (acc[city.continent] || 0) + 1
            return acc
        },
        {} as Record<string, number>,
    )

    return {
        All: cities.length,
        Asia: counts["Asia"] || 0,
        Europe: counts["Europe"] || 0,
        "North America": counts["North America"] || 0,
        "South America": counts["South America"] || 0,
        Africa: counts["Africa"] || 0,
        Oceania: counts["Oceania"] || 0,
        "Middle East": counts["Middle East"] || 0,
    }
}
